
name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push to ACR
        run: |
          docker build -t acrflaskv4.azurecr.io/acrflaskv4:${{ github.sha }} .
          docker push acrflaskv4.azurecr.io/acrflaskv4:${{ github.sha }}

  deploy-to-aci:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        run: |
          az login  --service-principal --tenant ${{ secrets.AZURE_TENANT_ID }} --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: acigroupv4
          dns-name-label: appversion4
          image: acrflaskv4.azurecr.io/acrflaskv4:${{ github.sha }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: aciflaskv4
          restart-policy: Never
          location: 'Canada Central'
